### ISSUE TITLE
Netlify Preview Deploy

### ISSUE THREAD

**Issue by iwandejong** [COS301-SE-2024/Crop-Prediction-System#170]
Maybe we can add this to test deployments on the `dev` branch before making a PR to main. @Tiaan2 you said it might be possible

**Comment by Tiaan2** [comment]
Attacthed is a picture regarding preview deploys i have setup. It deploys when a pr is made to main.
<img width="817" alt="Screenshot 2024-08-15 at 10 16 56" src="https://github.com/user-attachments/assets/f987733d-40e3-4d0e-8d1f-3d6a5d01e8f9">
