### ISSUE TITLE
Add Google Map Places API to cloud console

### ISSUE THREAD

**Issue by Xavier893** [COS301-SE-2024/Crop-Prediction-System#173]
Please add the places api to the cloud console, will enable more features like searching for the maps interface

**Comment by iwandejong** [comment]
<img width="450" alt="image" src="https://github.com/user-attachments/assets/1f003c1a-5aa5-4d30-b019-89f5002af69f">
Weird, on Cloud Console it says that Places are enabled, specifically for the API key we're using as well. Can you maybe send a screenshot for the message that you get?
