### ISSUE TITLE
Fix getTeamID API endpoint

### ISSUE THREAD

**Issue by Xavier893** [COS301-SE-2024/Crop-Prediction-System#190]
Me and @Tiaan2 have come across this issue where we can't get our team id (happened to me on the deployed version with demo 3) and @Tiaan2 can't access his page. I've tried a manual call with his user_id and the API returned user not found, so something is wrong there.

One possible fix is for me to fetch the team_id straight from supabase as a proxy call. Here is some code I've tested that seems to be working: 

```typescript
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = useRuntimeConfig().public.supabaseUrl
const supabaseKey = useRuntimeConfig().public.supabaseKey
const supabase = createClient(supabaseUrl as string, supabaseKey as string)

export default defineEventHandler(async (event) => {
  try {
    const { data, error } = await supabase
      .from('profiles')
      .select('team_id')
      .eq('email', getQuery(event).email)
      .single()
    if (error) {
      throw error
    }
    return data.team_id
  } catch (error: any) {
    return {
      statusCode: error.response?.status || 500,
      message: error.message,
    }
  }
})
```

Another option is maybe to use the user's email address as the input parameter to the api call (as emails are always unique)

**Comment by iwandejong** [comment]
I confirmed just now that the deployed `/getTeamId` endpoint is working to get the TeamID.

@Tiaan2's account doesn't have any fields, therefore there's no data:

<img width="703" alt="image" src="https://github.com/user-attachments/assets/977e1678-4b69-411e-ab9a-4bbb40f0a559">

Also, we're violating the layered architecture when doing proxy calls directly to the database, so I'd not prefer not to do it that way.

Will send the rest of the message on Discord
