### ISSUE TITLE
Add Team Endpoint and adjust addToTeam endpoint

### ISSUE THREAD

**Issue by Xavier893** [COS301-SE-2024/Crop-Prediction-System#206]
Please add a team endpoint with the following specifications:

Be able to view all members in a team with each team members details with something like /getTeamDetails:
- email address
- role
- full name

Adding a team member is in a working state with the implementation we discussed. However, I would please like a small change to the /addToTeam endpoint. Please add another key-value pair in the request body for "role" so that the new request body would look something like this:

```json
{
    "team_id": "592a7e6e-85f7-4830-8f1a-d2f396353a4b",
    "user_id": "0f543694-dba7-4858-bb34-23e88c844b77",
    "role": "farmer"
}
```

This will simplify the invite process and save an extra call to the api.

**Comment by Xavier893** [comment]
Just one more endpoint as well please. Something like a /getRole to get the user's role so that we can do prevention on certain actions in the app @iwandejong

**Comment by iwandejong** [comment]
> Just one more endpoint as well please. Something like a /getRole to get the user's role so that we can do prevention on certain actions in the app @iwandejong 

Can I return it together with the /getTeamID endpoint? 
E.g.
```json
{
> team_id: "",
> role: ""
}

**Comment by iwandejong** [comment]
Since you're storing that already...

**Comment by Xavier893** [comment]
Yeah that should be fine, if it's a new endpoint or just adjusting this one it should work the same. If you want to separate it for clarity we can do that otherwise just edit the /getTeamID @iwandejong

**Comment by iwandejong** [comment]
Perfect. Will deploy before the end of the day👍

**Comment by iwandejong** [comment]
Done. You can view the updated API documentation on Postman.

Here's a list of changes:
- `/getTeamId` now returns the role as well.
- `/getTeamDetails` returns the entire team's details (`full_name`, `email` and `role`).
- `/updateRoles` still exists should you want to update a user's `role` that is already in a team.
- `/addToTeam` now requires a `role` to be entered as well.

Please note that the (only) accepted roles are: `farm_manager`, `farmer`, `data_analyst`, `unassigned`.

If you're happy, you can close this issue👌
