### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by Xavier893** [COS301-SE-2024/Crop-Prediction-System#227]
### LogsView @Tiaan2 
- [x] fix logs view mobile errors for the toolbar at the top (not mobile responsive)
- [x] fix logs view export on mobile (tested on my phone and the checks don't register)

### Field Edit @Xavier893 
- [x] fix field map edit mode (when you click on the modal while doing a field edit button status is wrong)
- [x] fix ux consistency on buttons in field edit mode

### Team Management @Xavier893 
- [x] fix the team name to be 'My Team'
- [x] fix the logged in user not shown in team

### Toasts @Xavier893 
- [x] fix size of toast for mobile devices

**Comment by Tiaan2** [comment]
I believe I fixed the bugs, i changed the toolbars layout and some styling and looks to be working fine on mobile now.

And then on my mobile the clicks and exporting are registering and exporting the correct fields currently. So i'll maybe just have to sit with you and see if the errors persist on your end
