### ISSUE TITLE
Fix New Field Data Not Found

### ISSUE THREAD

**Issue by Xavier893** [COS301-SE-2024/Crop-Prediction-System#245]
I have an error when creating a new field. Did some testing on code refactoring for the Maps Interface and logging the Field Map. Everything worked smoothly with the creation and the field was added to the db in the correct manner, but it has no data. 

The `/getFieldInfo` works so creating fields works perfectly, but `/getFieldData` fails. After investigation, no data is available for the newly created field in the `data` table, leading to the fail of the api call.

Please have a look at this and fix it.

**Comment by iwandejong** [comment]
Would you prefer an appropriate API response to that or would you prefer at least some data when a new field is created?

**Comment by Xavier893** [comment]
Rather have some data for the field please, otherwise a lot needs to change for the frontend. And I think it's better because showcasing creating a field in the demo would be better with some data

**Comment by Xavier893** [comment]
Even if it's just the weather data for 8 days without any predictions on health, yield and sprayability

**Comment by iwandejong** [comment]
I'll make the [POST] /createField endpoint to request some weather data upon creation👍

**Comment by iwandejong** [comment]
Call /fetchWeather and /fetchSummary on field creation
