### ISSUE TITLE
Market Data Endpoints

### ISSUE THREAD

**Issue by Xavier893** [COS301-SE-2024/Crop-Prediction-System#248]
### Total Crop Hectare
- [ ] [GET] /totalWheatHectare
- [ ] [GET] /totalMaizeHectare

This needs to return the total ha of all user wheat and maize fields. 
#### Example:

User has the following Maize fields:

Field 1:
- 4ha

Field 2:
- 2ha

[GET] /totalMaizeHectare returns 6 = (4ha + 2ha)

---

### Total Crop TPH
- [ ] [GET] /totalWheatYield
- [ ] [GET] /totalMaizeYield

This needs to return the total current (today's) pred_yield for the specified crop type across all related fields. 
#### Example:

User has the following Maize fields:

Field 1:
- 3tph yield

Field 2:
- 2.5tph yield

[GET] /totalMaizeYield returns 5.5 = (3thp + 2.5tph)

---

### Total Crop Yield
- [ ] [GET] /totalWheatProduction
- [ ] [GET] /totalMaizeProduction

This needs to return the total yield production of crop types based on all user related field sizes (ha) and pred_yield (tph). Can be used for the total expected revenue for each crop type and a bigger overview of revenue expected for all fields with the appropriate crop types. 

#### Example:

User has the following Maize fields:

Field 1:
- 4ha
- 3tph yield

Field 2:
- 2ha
- 2.5tph yield

[GET] /totalMaizeProduction returns 17 = (4ha*3thp + 2ha*2.5tph)

---
If a user doesn't have maize or wheat fields, then the response can return something like 'user has no xxx fields'. Also, if you think this can be simplified, please don't hesitate to do so XD. I'm sure this can be optimized but this is just a general idea of everything that I need.

**Comment by iwandejong** [comment]
Done
